# Generated by Django 2.1 on 2018-08-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180816_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
